version: "3.8"

services:
  db:
    image: mariadb:10.6.14
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: P@ssw0rd
      MARIADB_DATABASE: url_shortener
      MARIADB_USER: app_user
      MARIADB_PASSWORD: P@ssw0rd

  app:
    build: .
    restart: on-failure
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mariadb://db/url_shortener
      DB_USERNAME: app_user
      DB_PASSWORD: P@ssw0rd